### ISSUE TITLE
Conflicts when used inside Rails app, by overwriting methods from ActiveSupport

### ISSUE THREAD

**Issue by axtro** [pjdavis/roart#1]
The Hash and String extensions used by roart overwrite the same extensions from ActiveSupport when used inside a Rails app. Roart for example defines 'camelize' on String without parameters, but ActiveSupport does use a parameter and Rails depends on the parameter for example in rjs views.

In http://github.com/hennk/roart/commit/054ccae71fb911a0cd749b1534f4ab5c48351b7c I fixed this by checking for existence of ActiveSupport before extending these system classes, allowing roart to be used from inside a Rails app.

**Comment by axtro** [comment]
The method Array#to_hash added by roart to Hash also conflicts with ActiveSupport's deep_merge, converting all arrays contained in the Hash to hashes

**Comment by pjdavis** [comment]
This is hopefully fixed in version 0.1.9 with the commit you referenced. Let me know if you run into any problems with it.
