### ISSUE TITLE
Not working when using new-lines in ticket fields

### ISSUE THREAD

**Issue by axtro** [pjdavis/roart#2]
Ticket creation fails if any field contains new lines. It seems that RT expects new-lines to be space-padded in order to distinguish them from the beginning of a new field. I have a commit at http://github.com/axtro/roart/commit/cd7dd269f6c0706921409654f9c6668332601382 which fixes this.

**Comment by pjdavis** [comment]
Awesome, thanks for the patch :) This is fixed.
